#! /bin/sh
### BEGIN INIT INFO
# Provides: noip
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: noip server
# Description:
### END INIT INFO

case "$1" in
    start)
        echo "photo_cloud wird gestartet"
        # Starte Programm
	cd /home/pi/photo_cloud/
        sudo python PhotoServerPy.py&
	sudo python PhotoRecPy.py&
        ;;
    stop)
        # Beende Programm
        ;;
    *)
        # sonst
        ;;
esac

exit 0
